### ISSUE TITLE
yaml file replace image name and tag

### ISSUE THREAD

**Issue by umar-siddiqui-ivolve** [DevOpsLK/eks-codepipeline-cicd#6]
- sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY:$TAG"'@' Kubernetes/eks-deployment.yml
- this command is not changing the YAML file image tag please fix asap

**Comment by umar-siddiqui-ivolve** [comment]
any update?
i m waiting your answer

**Comment by awsfanboy** [comment]
`[ec2-user@ip-172-31-81-162 eks-codepipeline-cicd]$ REPOSITORY=11111111111111.dkr.ecr.ap-southeast-2.amazonaws.com/testing_repo
[ec2-user@ip-172-31-81-162 eks-codepipeline-cicd]$ TAG=v1.2
[ec2-user@ip-172-31-81-162 eks-codepipeline-cicd]$ echo $REPOSITORY
11111111111111.dkr.ecr.ap-southeast-2.amazonaws.com/testing_repo
[ec2-user@ip-172-31-81-162 eks-codepipeline-cicd]$ echo $TAG
v1.2
[ec2-user@ip-172-31-81-162 eks-codepipeline-cicd]$ sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY:$TAG"'@' Kubernetes/eks-deployment.yml
[ec2-user@ip-172-31-81-162 eks-codepipeline-cicd]$ cat Kubernetes/eks-deployment.yml `
---
`apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eks-demo
  name: deployment-eks-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-eks-demo
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-eks-demo
    spec:
      containers:
      - image: 11111111111111.dkr.ecr.ap-southeast-2.amazonaws.com/testing_repo:v1.2
        imagePullPolicy: Always
        name: app-eks-demo
        ports:
        - containerPort: 80`

hi @umar-siddiqui-ivolve  this is a very basic sed command and i have tested already as above. no errors and it replaced the "CONTAINER_IMAGE". you have not provided sufficient information including the exact error. hence i am closing this issue as a false issue.

**Comment by umar-siddiqui-ivolve** [comment]
Dear Team,

It is working fine on Linux but not working in the cloud build I was not updating the YAML file tag or replace.

[cid:8b7aceae-e0b6-4949-bbc1-cdb885ce8e1a]




Regards,


[cid:4fb64c1c-a291-4bf5-aebe-d12b6b1146d4]

Muhammad Umar Siddiqui
Sr. DevOps Engineer

Mobile: +92307-2757483
+92 21 111 iVolve (486-583)<tel:+92%2021%20111%20486-583> | ***@***.***

www.ivolve.io<http://www.ivolve.io/>

NGC Tower, 3rd Floor, Plot #A-1, Block-3 7/8 KECHS,
Jinnah Housing Society, PECHS, Karachi, 75000, Pakistan

________________________________

**Comment by awsfanboy** [comment]
Sorry not getting you clearly, please do provide the errors more specifically.

**Comment by umar-siddiqui-ivolve** [comment]
Dear

It not giving me error but it is not updating the tag please see the below screenshot

can we call?


Regards,


[cid:7c01bde6-6e7c-4ea7-913e-156c752b2987]

Muhammad Umar Siddiqui
Sr. DevOps Engineer

Mobile: +92307-2757483
+92 21 111 iVolve (486-583)<tel:+92%2021%20111%20486-583> | ***@***.***

www.ivolve.io<http://www.ivolve.io/>

NGC Tower, 3rd Floor, Plot #A-1, Block-3 7/8 KECHS,
Jinnah Housing Society, PECHS, Karachi, 75000, Pakistan

________________________________

**Comment by damithkothalawala** [comment]
do an echo to get the sed location 1st and check for the sed binary 1st
`    commands:
      - echo `which sed`
 `

**Comment by damithkothalawala** [comment]
echo `which sed`

**Comment by damithkothalawala** [comment]
> 

upload screenshot at https://github.com/DevOpsLK/eks-codepipeline-cicd/issues/6 do not reply to the email

**Comment by umar-siddiqui-ivolve** [comment]
[Container] 2022/12/29 07:35:34 Running command cat aetius-ui-deployment.yaml \|grep -i image
--
117 | - image: 732352859943.dkr.ecr.us-east-1.amazonaws.com/aetius-ui:49
118 | imagePullPolicy: IfNotPresent
119 |  
120 | [Container] 2022/12/29 07:35:34 Running command sed -i 's@$REPOSITORY@'"$REPOSITORY:$TAG"'@' aetius-ui-deployment.yaml
121 |  
122 | [Container] 2022/12/29 07:35:34 Running command cat aetius-ui-deployment.yaml \|grep -i image
123 | - image: 732352859943.dkr.ecr.us-east-1.amazonaws.com/aetius-ui:49
124 | imagePullPolicy: IfNotPresent
125 |  
126 | [Container] 2022/12/29 07:35:34 Running command git add .
127 |  
128 | [Container] 2022/12/29 07:35:34 Running command git commit -m "Update docker image by code Build UI:'$TAG'"
129 | On branch main
130 | Your branch is up to date with 'origin/main'.
131 |  
132 | nothing to commit, working tree clean

**Comment by umar-siddiqui-ivolve** [comment]
please check

**Comment by umar-siddiqui-ivolve** [comment]
sed -i 's+${registry}.*+${registry}:${BUILD_NUMBER}+g' cron-deployment.yaml also this command is working in my jenkins pipeline but codebuild also not update tag using this command

**Comment by damithkothalawala** [comment]
@devopswithzack seems something to do with codebuild env. nothing wrong with your code.

**Comment by umar-siddiqui-ivolve** [comment]
what should i do?

**Comment by umar-siddiqui-ivolve** [comment]
how can i achive that

**Comment by awsfanboy** [comment]
@umar-siddiqui-ivolve this error nothing to do with our code here. in my testing environment this codebuild is working without any issues. i do recommend you to follow some basic troubleshooting in your build-spec eg: print the env variables and etc. since there is no issue with our buildspec.yaml we are closing this. thanks 
check these AWS docs : https://docs.aws.amazon.com/codebuild/latest/userguide/welcome.html
